### ISSUE TITLE
Error while building from source code of Faunus 2.4.1

### ISSUE THREAD

**Issue by directysj** [mlund/faunus#355]
Hello Faunus team,

I am building Faunus from the source code to add OpenMp pragma for the parallelization of energies. I am using the options for cmake as:
cmake . -DENABLE_OPENMP=ON -DENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX:PATH=/home/user/localInstall/tstFaunusInstOpenMP -DPYTHON_EXECUTABLE=/home/user/anaconda3/envs/faunus-env/bin/python3.6 -DPYTHON_INCLUDE_DIR=/home/user/anaconda3/envs/faunus-env/include/python3.6m -DPYTHON_LIBRARY=/home/user/anaconda3/envs/faunus-env/lib

This is giving error: 

The requested URL returned error: 404
stopped the pause stream!
 Connection #1 to host bitbucket.org left intact
       --- LOG END ---
make[2]: *** [CMakeFiles/eigen-populate.dir/build.make:91: eigen-populate-prefix/src/eigen-populate-stamp/eigen-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/eigen-populate.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

CMake Error at /usr/share/cmake-3.13/Modules/FetchContent.cmake:798 (message):
  Build step for eigen failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FetchContent.cmake:889 (__FetchContent_directPopulate)
  CMakeLists.txt:207 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!

Can you help me out in this case?

**Comment by mlund** [comment]
It's because the Eigen library moved to a new website, so the url is unfortunately broken. There's a patch for this, but it was never published as a release:

https://github.com/mlund/faunus/tree/v2.4.2

If you do not have a particular reason to use v2.4.x, I suggest you try the development version (`master`). Most of the changes for [v2.5.0](https://github.com/mlund/faunus/milestone/4)  soon to be released.

**Comment by directysj** [comment]
Thank you so much for the help. I can use development version ( `master` )  .
